### ISSUE TITLE
UpgradeData for terran mech armor upgrades map to the wrong research ability

### ISSUE THREAD

**Issue by Ketroc** [ocraft/ocraft-s2client#22]
Upgrades.TERRAN_VEHICLE_AND_SHIP_ARMORS_LEVEL1 is currently mapped to RESEARCH_TERRAN_VEHICLE_AND_SHIP_PLATING_LEVEL1_V2 in UpgradeData.getAbility().

The correct ability is: RESEARCH_TERRAN_VEHICLE_AND_SHIP_PLATING_LEVEL1. ( no, "_V2" on the end)

The same applies for LEVEL2 and LEVEL3.

**Comment by ocraft** [comment]
I'm not sure that it's a bug, the mapping is based only on what the game server provides and the API itself has nothing to say in that matter. You can check all of the game mappings in \Documents\StarCraft II\stableid.json file and compare id to the name. Unfortunately, sometimes different game paths or game versions or maps have a different id for the same or similar upgrade/ability/unit because of some changes, and API can do nothing about that, only make a distinction with suffix, like _V2 in this example. There was a similar issue (but in the opposite direction) some time ago https://github.com/ocraft/ocraft-s2client/issues/8.
